require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Max: 200

CyclomaticComplexity:
  Enabled: false

PerceivedComplexity:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/FilePath:
  Enabled: false

convention:Metrics/BlockLength:
  Max: 70

Rails/HttpPositionalArguments:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

